config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'
  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]

    post :show, on: :member
  end
  resources :photos
  resources :users, only: %i[show edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook vkontakte]

  # Юзер может создавать много событий
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  validates :name, presence: true, length: { maximum: 35 }

  validates :email, length: { maximum: 255 },
            uniqueness: true,
            format: /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    user = where(email: auth.info.email).first
    user ||= create!(provider: auth.provider, uid: auth.uid, name: auth.info.name.split.first,
                     email: auth.info.email, remote_avatar_url: auth[:info][:image],
                     password: Devise.friendly_token[0, 20])
    user
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  private

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email)
                .update_all(user_id: self.id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def vkontakte
      authenticate_user(:vkontakte)
    end

    def facebook
      authenticate_user(:facebook)
    end

    def authenticate_user(provider)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: provider)
      else
        flash[:error] = I18n.t(
          'devise.omniauth_callbacks.failure',
          kind: 'provider',
          reason: 'authentication error'
        )
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>

  <%= render partial: 'partials/form_errors', locals: { model: @user } %>

  <div class="mb-3">
    <%= f.label :Имя %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :avatar %>
    <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-success' %> <%= link_to 'Вернуться', :back, class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form', user: @user %>

    <p class="buffer-top">
      <%= link_to 'Сменить пароль', edit_user_registration_path, class: 'btn btn-secondary' %>
    </p>

  </div>
</div>

app/views/users/index.html.erb
<% if notice.present? %>
  <div class="buffer-top alert alert-success alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% if notice.present? %>
  <div class="buffer-top alert alert-success alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div class="text-center">
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user) %>

  <% if @user == current_user %>
    <p class="buffer-top">
      <%= link_to 'Редактировать профиль', edit_user_path(@user), class: 'btn btn-secondary' %>
    </p>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <% if @user.events.any? %>
        <h3>Организовал:</h3>
        <div class="row">
          <%= render partial: 'events/event', collection: @user.events %>
        </div>
      <% else %>
        <p class="buffer-top">Пользователь пока не организовал ни одного
          события</p>
      <% end %>
    </div>
  </div>
</div>