config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'
  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]

    post :show, on: :member
  end
  resources :photos
  resources :users, only: %i[show edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true, length: { maximum: 50 }, format: /[[:word:]-]+/
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[show edit update destroy]
  after_action :verify_authorized, only: %i[edit update destroy show]

  def index
    @events = Event.all
  end

  def show
    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    begin
      authorize @event
    rescue Pundit::NotAuthorizedError
      flash.now[:alert] = t('controllers.events.wrong_pincode') if params[:pincode].present?
      render 'password_form'
    end

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/views/events/_event.html.erb
<%# Паршиал для отображения инфы об отдельном событии %>
<div class="col-sm-6 col-md-4 buffer-bottom">
  <div class="thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_pack_path('media/images/event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3 class="text-center"><%= link_to event.title, event_path(event) %></h3>
          <h4 class="buffer-top"><small><%= l event.datetime, format: :short %></small></h4>
          <div><%= event.address %></div>
        </div>
      </div>
      <div>
        <%# Выводим всех пользователей, которые придут на событие, выводя их аватарки %>
        <% event.visitors.each do |user| %>
          <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%# Паршиал дляотображения формы создания нового события %>
<%= form_for(@event) do |f| %>

  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="mb-3">
    <%= f.label :Название %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :Адрес %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :Время_события %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="mb-3">
    <%= f.label :Описание %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-success' %>
    <%= link_to 'Вернуться', :back, class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t('edit_event') %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<% if notice.present? %>
  <div class="buffer-top alert alert-success alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <p id="notice"><%= notice %></p>
  </div>
<% end %>

<h1>События</h1>

<div class="buffer-both">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%# Рендерим сразу массив событий, каждый в паршиале 'events/event' %>
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<% if alert.present? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <p><%= alert %></p>
  </div>
<% end %>

<h1>Доступ только по пин-коду</h1>

<%= form_tag('', method: 'post') do |f| %>
  <div class="mb-3">
    <%= label 'Пин-код', :pincode %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag 'Ввод', class: 'btn btn-success' %>
    <%= link_to 'Вернуться', :back, class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/events/show.html.erb
<% if notice.present? %>
  <div class="buffer-top alert alert-success alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div class="event">
  <div class="event-info buffer-top">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background', style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6 buffer-left">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3><small><%= link_to @event.address,
                                   "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>
          <div class="buffer-both">
            <%= link_to t('events_page'), events_path, class: 'btn btn-secondary' %>
          </div>
          <% if current_user_can_edit?(@event) %>
            <div class="buffer-both">
              <%= link_to t('edit_event'), edit_event_path(@event), class: 'btn btn-success' %>
              <%= link_to t('delete'), event_path(@event), method: :delete, data: {confirm: t('are_you_sure')},
                          class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10">
      <div id="map" style="width: auto; height: 300px"></div>
      <div class="event-photos">
        <%# Выводим все фотографии события %>
        <div class="event-photos-gallery event-photo buffer-both">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>

        <%# Рисуем форму для добавления новой фотографии %>
        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
        </div>
      </div>

      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form',
                   locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment',
                     collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-2 text-start">
      <div class="event-owner">
        <h4>Зовет:</h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h4>Пойдут:</h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
                       collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <% if @event.user == current_user %>
        <div>
          <h6>Вы инициатор события!</h6>
        </div>
      <% else %>
        <div class="event-subscription-form">
          <h6>Я пойду:</h6>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
              subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  ymaps.ready(init);

  function init() {
    let myMap = new ymaps.Map('map', {
      center: [44.006516, 37.617110],
        zoom: 12
    });

  // Поиск координат.
  ymaps.geocode('<%= @event.address %>>', {
    results: 1
    }).then(function (res) {
      let firstGeoObject = res.geoObjects.get(0),
        coords = firstGeoObject.geometry.getCoordinates(),
        bounds = firstGeoObject.properties.get('boundedBy');

      firstGeoObject.options.set('preset', 'islands#darkBlueDotIconWithCaption');
            // Получаем строку с адресом и выводим в иконке геообъекта.
      firstGeoObject.properties.set('iconCaption', firstGeoObject.getAddressLine());

      myMap.geoObjects.add(firstGeoObject);
      myMap.setBounds(bounds, {
        checkZoomRange: true
        });

      let myPlacemark = new ymaps.Placemark(coords, {
        iconContent: '<%= @event.title %>',
        balloonContent: '<%= @event.description %>'
      }, {
        preset: 'islands#violetStretchyIcon'
      });

      myMap.geoObjects.add(myPlacemark);
        });
    }
</script>