config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'
  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]

    post :show, on: :member
  end
  resources :photos
  resources :users, only: %i[show edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :event, presence: true
  validates :user, presence: true
  validates :photo, presence: true, format: /[a-zA-Zа-яА-Я\-_0-9\/\:\.]*/i

  mount_uploader :photo, PhotoUploader

  # Этот scope нужен нам, чтобы отделить реальные фотки от болванки
  scope :persisted, -> { where 'id IS NOT NULL' }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # Для каждого действия нужно получить событие, к которому привязана фотография
  before_action :set_event, only: [:create, :destroy]

  # Для действия destroy нужно получить из базы саму фотографию
  before_action :set_photo, only: [:destroy]

  def create
    # Создаем новую фотографию у нужного события @event
    @new_photo = @event.photos.build(photo_params)

    # Проставляем у фотографии пользователя
    @new_photo.user = current_user

    if @new_photo.save
      EventEmailNotificationJob.perform_later(@new_photo)
      # Если фотографию удалось сохранить, редирект на событие с сообщением
      redirect_to @event, notice: I18n.t('controllers.photos.created')
    else
      # Если фотографию не удалось сохранить, рендер события с ошибкой
      render 'events/show', alert: I18n.t('controllers.photos.error')
    end
  end

  # Действие для удаления фотографии
  def destroy
    message = { notice: I18n.t('controllers.photos.destroyed') }

    # Проверяем, может ли пользователь удалить фотографию
    # Если может — удаляем, нет, меняем сообщение
    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = { alert: I18n.t('controllers.photos.error') }
    end

    # И в любом случае редиректим его на событие
    redirect_to @event, message
  end

  private
  # Так как фотография — вложенный ресурс, то в params[:event_id] рельсы
  # автоматически положает id события, которому принадлежит фотография
  # найденное событие будет лежать в переменной контроллера @event
  def set_event
    @event = Event.find(params[:event_id])
  end

  # Получаем фотографию из базы стандартным методом find
  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  # При создании новой фотографии мы получаем массив параметров photo
  # c единственным полем (оно тоже называется photo)
  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end
end

app/views/photos/_form.html.erb
<%# Форма для добавления новой фотографии с одним полем photo %>
<%# Обратите внимание на параметр multipart %>
<%= form_for [@event, photo], html: { multipart: true } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: photo} %>

  <div class="mb-3">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit 'Загрузить', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<% image_title = "#{t('.add')} #{render partial: 'users/user', object: photo.user}" %>
<% if current_user_can_edit?(photo) %>
  <% delete_icon = link_to(fa_icon('trash'), event_photo_path(photo.event, photo), method: :delete, data: {confirm: t('.destroy_confirm')}) %>
  <% image_title << delete_icon %>
<% end %>

<% if photo.photo.url.present? %>
  <%= link_to image_tag(photo.photo.thumb.url), photo.photo.url, data: {lightbox: 'roadtrip', title: image_title, alt: 'photo'} %>
<% end %>